// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repositories.EFCore;

#nullable disable

namespace WebAPI.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    [Migration("20230223125951_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Entities.Models.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Genre")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ReleaseYear")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Genre = 2,
                            Name = "Gladiator",
                            Price = 88m,
                            ReleaseYear = 2000
                        },
                        new
                        {
                            Id = 2,
                            Genre = 3,
                            Name = "Kingdom of Heaven",
                            Price = 98m,
                            ReleaseYear = 2005
                        },
                        new
                        {
                            Id = 3,
                            Genre = 6,
                            Name = "Pokemon Detective Pikachu",
                            Price = 67m,
                            ReleaseYear = 2019
                        },
                        new
                        {
                            Id = 4,
                            Genre = 1,
                            Name = "Geniş Aile",
                            Price = 102m,
                            ReleaseYear = 2015
                        },
                        new
                        {
                            Id = 5,
                            Genre = 4,
                            Name = "Saw",
                            Price = 105m,
                            ReleaseYear = 2004
                        },
                        new
                        {
                            Id = 6,
                            Genre = 5,
                            Name = "Avatar",
                            Price = 107m,
                            ReleaseYear = 2009
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
